[package]
name = "juice-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.4.0"
derive_more = { workspace = true }
lasso = "0.7.2"
